### PR TITLE
Joystick emulation via keyboard shouldn't be affected by renumbering

### PR DESCRIPTION
**Pull request by gyurco**
I fail to see why the joystick emulation should be changed when I plug in an USB stick. But maybe has a reason?
Also don't send digital events continuously. It just interferes with joy emu.

### CODE REVIEW

**Comment by harbaum** [comment]
The idea was that the emulated joystick would be an additional one. So if you e.g. plug two usb joysticks you could use the keyboard emulation as a third one.

**Comment by gyurco** [comment]
Make sense from that point of view. My use case is I don't have to disconnect my USB joysticks to use the joy emu.

**Comment by gyurco** [comment]
Maybe I'll add a mist.ini option "joy_emu_follows_db9", default 1. Or idea for a better name?

**Comment by gyurco** [comment]
Added joystick_emu_fixed_index (default behaviour not changed)
And also discovered some issues with ini parsing.
Merging, shout if some parts should be reverted.

**Pull request merged**
