### PR TITLE
Update user_io.c

### PR DESCRIPTION
**Pull request by Gamusino78**
I want to remove these lines because they have an error in the line ... 1584 "uer" _io_send_buttons (1); ... thanks.

### CODE REVIEW

**Comment by gyurco** [comment]
You can correct your commit, amend it, then force push to your repo, it'll be automatically changed in the pull request. Btw, a description what it does would be nice instead of "Update user_io.c"

**Comment by Gamusino78** [comment]
modified... function: Patch: to use shortcut CTRL + ALT + CTRL to enable / disable scandoubler

**Comment by gyurco** [comment]
Is it a good idea? Ctrl-Alt-Del could be a legitimate use by a core. Also scandoubler can be toggled by the middle button already.

**Comment by harbaum** [comment]
Indeed. That why we are using the most esoteric keys for menus and the like as we try to avoid anything that might be needed in regular use cases.

Alt/Ctrl/Del is a very popular combo and e.g. the Atari ST uses it natively.

**Comment by Gamusino78** [comment]
Yes, the combination that you propose is a better solution, you can make the modification without problem.

**Comment by gyurco** [comment]
Closing as it seems abandoned.

**Comment by harbaum** [comment]
I totally missed that he suggested ctrl-alt-ctrl instead of ctrl-alt-del. I still think that ctrl-alt-ctrl may also have a use case in a real machine. Although most of them don't even have a second ctrl key. I'd have to check if the amigas had one ...

**Comment by gyurco** [comment]
Probably not used, but it would be equally easy to set up a list of combos, and add a mist.ini option to choose from them (similarly to the reset combo).

**Pull request closed without merging**
