### PR TITLE
Show information of booted storage device in OSD system menu

### PR DESCRIPTION
**Pull request by retrofun**
Now that we have several variants of boot storage devices (SD/USB, FAT file systems) it may be handy to display some information about it in the OSD system menu, e.g.:

<pre>
SD  /     30436MB / FAT32
</pre>
<pre>
SD  /    121942MB / EXFAT
</pre>
<pre>
USB /       991MB / FAT16
</pre>
<pre>
USB /     14999MB / FAT32
</pre>

### CODE REVIEW

**Comment by gyurco** [comment]
Thanks, but I'm not convinced about the aesthetics of the new line in the system menu.

**Comment by gyurco** [comment]
Maybe better place would be in the About box?

**Comment by retrofun** [comment]
@gyurco: How about a system status page?

mist_system_status_600

https://github.com/retrofun/mist-firmware/tree/system_status_page

**Comment by gyurco** [comment]
Looks very nice!

I don't know if the generalized USB info collection is needed: for the purpose of the status page, it's enough to add accessors to hid.c/mice and pl2303.c/adapter_count.
But finding out the MAC would require to traverse through the USB tree anyway, so maybe it's OK to keep.

**Comment by retrofun** [comment]
I thought of direct access some time ago, too.
But I decided to extend the usb_hid_class list with an ID and name because it also adds nicer debug output like
```
trying to init class hub
usb_hub_init()
not a hub!
 -> not accepted :-(
trying to init class hid
HID: usb_hid_init(2)
HID: no hid interfaces found
 -> not accepted :-(
trying to init class xbox
 -> not accepted :-(
...
```
instead of just class numbers
```
trying to init class 0
usb_hub_init()
not a hub!
 -> not accepted :-(
trying to init class 1
HID: usb_hid_init(5)
HID: no hid interfaces found
 -> not accepted :-(
trying to init class 2
 -> not accepted :-(
...
```
and then parse the USB dev list.

But yes, it works with accessors to mice, keyboards, adapter_count and even mac address, too, because only 1 ethernet adapter is allowed for asix class.

If we want a compacter size of the firmware then this is the way to go.
https://github.com/retrofun/mist-firmware/tree/system_status_page_2

For me
* _system_status_page_ branch adds 884 bytes
* _system_status_page_2_ branch adds 736 bytes

to the firmware.

**Comment by gyurco** [comment]
150 bytes are nothing, it shoudn't be a problem. But I have another thing in my mind: with the USB tree traversal, the whole tree is walked for every line. However it's probably not an issue for the usual few USB devices connected.

**Pull request merged**
